### ISSUE TITLE
domino.patch fails to apply

### ISSUE THREAD

**Issue by jcwren** [domino-team/domino-firmware#4]
With domino.patch 97f1817ef0

```
$ quilt push -a
Applying patch domino.patch
patching file target/linux/ar71xx/base-files/lib/ar71xx.sh
Hunk #1 FAILED at 322.
1 out of 1 hunk FAILED -- rejects in file target/linux/ar71xx/base-files/lib/ar71xx.sh
patching file target/linux/ar71xx/base-files/lib/upgrade/platform.sh
Hunk #1 FAILED at 175.
1 out of 1 hunk FAILED -- rejects in file target/linux/ar71xx/base-files/lib/upgrade/platform.sh
patching file target/linux/ar71xx/files/arch/mips/ath79/mach-domino.c
patching file target/linux/ar71xx/generic/profiles/domino.mk
patching file target/linux/ar71xx/image/Makefile
patching file target/linux/ar71xx/patches-3.10/911-MIPS-ath79-add-domino-support.patch
patching file target/linux/ar71xx/config-3.10
patching file target/linux/ar71xx/base-files/etc/uci-defaults/02_network
patching file target/linux/ar71xx/base-files/etc/uci-defaults/01_leds
Hunk #1 FAILED at 119.
1 out of 1 hunk FAILED -- rejects in file target/linux/ar71xx/base-files/etc/uci-defaults/01_leds
Patch domino.patch does not apply (enforce with -f)
```

**Comment by alzhao** [comment]
which Openwrt version are you using? It should works only on BB1407. If you are applying on trunk, it is likely to have this issue.

**Comment by jcwren** [comment]
It was a whitespace issue caused by viewing the patch file in raw mode, and pasting into vim. 

Here's some updates to the instructions that would make them a little clearer.

Modifying the instructions in step 1 of https://github.com/domino-team/docs/blob/master/pi/compile.md to include

```
git clone https://github.com/domino-team/domino-firmware.git
```

into the same directory where openwrt-domino is located.  Also remove the '#' from in front of the two `sudo` lines. If someone copy/pastes them, they're not going to do anything.

Remove the following line from step 3:

```
sudo apt-get install quilt
```

as it's already been installed in the first `apt-get`.  Exchange the order of steps 2 and 3.

Modify step 4 to read

```
mkdir patches
cp ../domino-firmware/domino-pi/openwrt/patches/domino.patch ./patches
cp ../domino-firmware/domino-pi/openwrt/patches/series ./patches
quilt push -a
rm -f ./tmp/*
./scripts/feeds install -a
```

Note that if the '-f' option is not specified, when `make menuconfig` is run, the Domino target will not appear.

Remove the following text from step 4:

```
In order to make the Target appear, you may need to run rm ./tmp/* and ./scripts/feeds install -a
```

In step 5, unless you're a `git` user (and remember, not everyone is), it's not obvious how to download that source tree. Since we've already cloned the domino-firmware repository in step 1, add explicit instructions on how to do it:

```
mkdir package/domino
cp -a ../domino-firmware/domino-pi/audio/* package/domino
cp -a ../domino-firmware/domino-pi/domino-pi package/domino
cp -a ../domino-firmware/domino-pi/mpg123 package/domino
mkdir files
cp -a ../domino-firmware/domino-pi//root-files/* files
```

Lastly, when building the pre-installed images, replace

```
Type make menuconfig and select domino specific packages.
```

with

```
Type make menuconfig, select 'domino' on the main menu (midway down), then select the Domino specific packages. These must be selected as compiled-in (*), not modules (M).
```

In the paragraph under the `make menuconfig` screen-shot, change from 

```
You will find "domino-athplay", "domino-pi" and "kmod-domino-iis" in "Domino" category. Select them all by pressing space key until it shows a * before the package.
```

to

```
Select the packages by pressing the space key until it shows a '*' before the package name.
```

**Comment by alzhao** [comment]
applied your changes. Sorry for so late.
