### ISSUE TITLE
Node v0.12.7 on Linux domino 3.18.21

### ISSUE THREAD

**Issue by yaseenox-personal** [domino-team/domino-firmware#6]
I installed node package from this link http://domino.io/firmware/pi/1.3/packages/packages/node_v0.12.7-1_ar71xx.ipk but I get this error when I try to run node script.
root@domino:/# node /test/helloWorld.js
Illegal instruction

can you help me please.

**Comment by alzhao** [comment]
Here is the compiled package which works. I will update the firmware.
[nodejs.zip](https://github.com/domino-team/domino-firmware/files/73051/nodejs.zip)
usage:
copy to your domino board, e.g. /tmp/
unzip them
then 

opkg update
opkg install *.ipk

**Comment by yaseenox-personal** [comment]
It works. thank you very much.

**Comment by yaseenox-personal** [comment]
root@domino:/# npm install aws-iot-device-sdk
-ash: npm: not found

Is possible to install packages from npm ?
